### ISSUE TITLE
jar hell exception after installing plugin

### ISSUE THREAD

**Issue by smirrom** [anti-social/jmorphy2#36]
OS: Astra Linux 1.6 Smolensk (aka Debian 9)
Packages:
elasticsearch                          7.17.6
elasticsearch-analysis-jmorphy2-plugin 0.2.3~es7.17.6

After jmorphy deb package install, elasticsearch cannot start, exception:
```
[ERROR][o.e.b.Bootstrap          ] [xxxxxx] Exception
java.lang.IllegalStateException: failed to load plugin analysis-jmorphy2 due to jar hell
        at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:691) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:531) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:170) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.node.Node.<init>(Node.java:411) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) [elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) [elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) [elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) [elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) [elasticsearch-cli-7.17.6.jar:7.17.6]
        at org.elasticsearch.cli.Command.main(Command.java:77) [elasticsearch-cli-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) [elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) [elasticsearch-7.17.6.jar:7.17.6]
Caused by: java.lang.IllegalStateException: jar hell!
class: org.apache.lucene.analysis.ar.ArabicAnalyzer$DefaultSetHolder
jar1: /usr/share/elasticsearch/plugins/analysis-jmorphy2/lucene-analyzers-common-8.9.0.jar
jar2: /usr/share/elasticsearch/lib/lucene-analyzers-common-8.11.1.jar
        at org.elasticsearch.jdk.JarHell.checkClass(JarHell.java:297) ~[elasticsearch-core-7.17.6.jar:7.17.6]
        at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:192) ~[elasticsearch-core-7.17.6.jar:7.17.6]
        at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:689) ~[elasticsearch-7.17.6.jar:7.17.6]
        ... 14 more

```

**Comment by anti-social** [comment]
В публичном репозитории ничего исправлять не планирую. Причиньі описаньі тут: https://github.com/anti-social/jmorphy2/issues/34#issuecomment-1475346497
